name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.17.0"

      # Step 3: Setup SSH and deploy with directory checks
      - name: Setup SSH and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: "root"
          key: ${{ secrets.SSH_KEY }}
          port: 22
          script: |
            echo "Current working directory:"
            pwd  # Hozirgi katalogni ko'rsatish
            echo "Listing files in the current directory:"
            ls -la  # Fayllarni ko'rsatish
            cd /root/kiosk_insurance/
            echo "After changing directory:"
            pwd  # Loyihaga o'tgandan keyin joriy katalogni ko'rsatish
            ls -la  # Loyiha papkasidagi fayllarni ko'rsatish
            git stash || { echo "git stash failed"; exit 1; }
            git pull origin main || { echo "git pull failed"; exit 1; }
            pnpm install
            pnpm build
            npx prisma migrate dev --name migrated
            npx prisma generate
            pm2 restart insurance

      # Step 4: Notify Telegram on success
      - name: Notify Telegram on success
        if: success()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CD Successfully.\\nCommit: $COMMIT_MESSAGE\\nAuthor: $COMMIT_AUTHOR"

      # Step 5: Notify Telegram on failure
      - name: Notify Telegram on failure
        if: failure()
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_AUTHOR=$(git log -1 --pretty=format:"%an")
          curl -s -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage \
          -d chat_id=${{ secrets.TELEGRAM_CHAT_ID }} \
          -d text="CD Failed.\\nCommit: $COMMIT_MESSAGE\\nAuthor: $COMMIT_AUTHOR"
